Controllers/ContatoController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace LivroEC_V2.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            if(User.Identity.IsAuthenticated)
            {
                return View();
            }

            return RedirectToAction("Login", "Account");
        }
    }
}

Controllers/LivroController.cs
using LivroEC_V2.Models;
using LivroEC_V2.Repositorio;
using LivroEC_V2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace LivroEC_V2.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroRepositorio _livroRepositorio;

        public LivroController(ILivroRepositorio livroRepositorio)
        {
            _livroRepositorio = livroRepositorio;
        }

        [Authorize]
        public IActionResult List(string categoria)
        {
            // Código para rederizar na view a quantidade de livros no banco
            ViewBag.TotalDeLivros = _livroRepositorio.Livros.Count();

            IEnumerable<Livro> livros;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                livros = _livroRepositorio.Livros.OrderBy(l => l.LivroId);
                categoriaAtual = "Todos os livros";
            }
            else
            {
                //if (string.Equals("Política", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    livros = _livroRepositorio.Livros
                //        .Where(l => l.Categorias.CategoriaNome
                //        .Equals("Política"))
                //        .OrderBy(l => l.Titulo);
                //}
                //else
                //{
                //    livros = _livroRepositorio.Livros
                //                   .Where(l => l.Categorias.CategoriaNome
                //                   .Equals("Romance"))
                //                   .OrderBy(l => l.Titulo);
                //}

                livros = _livroRepositorio.Livros
                    .Where(l => l.Categorias.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Titulo);

                categoriaAtual = categoria;
            }

            var livrosListViewModel = new LivroListViewModel
            {
                Livros = livros,
                CategoriaAtual = categoria
            };

            return View(livrosListViewModel);
        }

        public IActionResult Details(int livroId)
        {
            var livro = _livroRepositorio.Livros.FirstOrDefault(l => l.LivroId == livroId);
            return View(livro);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Livro> livros;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                livros = _livroRepositorio.Livros.OrderBy(x => x.LivroId);
                categoriaAtual = "Todos os livros";
            }
            else
            {
                livros = _livroRepositorio.Livros
                    .Where(x => x.Titulo
                    .ToLower()
                    .Contains(searchString
                    .ToLower()));

                if(livros.Any())
                {
                    categoriaAtual = "Livros";
                }
                else
                
                    categoriaAtual = "Nenhum livro foi encontrado";
                                       
            }

            return View("~/Views/Livro/List.cshtml", new LivroListViewModel
            {
                Livros = livros,
                CategoriaAtual = categoriaAtual
            }) ;
        }
    }
}         

Views/Shared/_Carousel.cshtml
<div id="carouselLivros" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="./images/Livro1.jpg" alt="...">
        </div>
        <div class="carousel-item">
            <img src="./images/Livro2.jpg" alt="...">
        </div>
        <div class="carousel-item">
            <img src="./images/Livro3.jpg" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselLivros" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselLivros" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LivroEC_V2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LivroEC_V2.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.7/datatables.min.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); font-size: 35px" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LivroEC_V2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @await Html.PartialAsync("_LoginPartial");
                        </li>
                        <li class="nav-item">
                            <a style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); color: #fff" class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); color: #fff" class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); color: #fff" class="nav-link text-light" asp-area="" asp-controller="Livro" asp-action="List">Livros</a>                 
                        </li>
                        <li class="nav-item">
                            <a style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); color: #fff" class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <li style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); color: #fff" class="nav-link text-light">Livro por Categoria:</li>
                        @await Component.InvokeAsync("CarrinhoCompraResumo");
                        @await Component.InvokeAsync("CategoriaMenu");
                        <li class="nav-item">
                            <form class="nav-form navbar-left" asp-controller="Livro" asp-action="Search" method="get">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]" />
                                </div>
                            </form>
                         
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy Desenvolvido por: <strong style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);">Márcio Rodrigo.</strong>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.7/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LivroResumo.cshtml
@model Livro

<td>
    @Html.DisplayFor(modelItem => @Model.Titulo)
</td>
<td>
    @Html.DisplayFor(modelItem => @Model.Preco)
</td>
@*<td>
    <img src="~/@Model.CaminhoImagem" alt="Imagem" />
</td>*@
@*<td>
    @Html.DisplayFor(modelItem => @Model.IsLivroPreferido)
</td>*@
@*<td>
    @Html.DisplayFor(modelItem => @Model.EmEstoque)
</td>*@
<td>
  @Html.DisplayFor(modelItem => @Model.Categorias.CategoriaNome)
</td>