Models/Livro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LivroEC_V2.Models
{
    [Table("Livros")]
    public class Livro
    {
        [Key]
        public int LivroId { get; set; }
        [Required(ErrorMessage = "O título deve ser informado")]
        [Display(Name = "Titulo do livro")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "O título deve ser informado")]
        [Display(Name = "Descrição do livro")]
        [MinLength(20, ErrorMessage = "Descrição deve ter no mínimo {1} caracteres")]
        [MaxLength(200, ErrorMessage = "Descrição não deve exceder {1} caracteres")]
        public string DescricaoCurta { get; set; }
        [Required(ErrorMessage = "Informe o preço do livro")]
        [Display(Name = "Preço R$")]
        [Column(TypeName = "decimal(10,2)")]
        [Range(1,999.99, ErrorMessage = "O preço deve estar entre 1 e 999,999")]
        public decimal Preco { get; set; }
        [Display(Name = "Imagem")]
        public string CaminhoImagem { get; set; }
        [Display(Name = "Preferido?")]
        public bool IsLivroPreferido { get; set; }
        [Display(Name = "Estoque")]
        public bool EmEstoque { get; set; }
        public int CategoriaId { get; set; }
        public virtual Categoria Categorias { get; set; }
    }
}

Controllers/CarrinhoCompraController.cs
using LivroEC_V2.Models;
using LivroEC_V2.Repositorio;
using LivroEC_V2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LivroEC_V2.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILivroRepositorio _livroRepositorio;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILivroRepositorio livroRepositorio, CarrinhoCompra carrinhoCompra)
        {
            _livroRepositorio = livroRepositorio;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();

            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraVewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal(),
            };

            return View(carrinhoCompraVM);
        }

        [Authorize]
        public IActionResult AdicionarItemDoCarrinhoCompra(int livroId)
        {
            var livroSelecionado = _livroRepositorio.Livros.FirstOrDefault(l => l.LivroId == livroId);

            if(livroSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(livroSelecionado);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int livroId)
        {
            var livroSelecionado = _livroRepositorio.Livros.FirstOrDefault(l => l.LivroId == livroId);

            if (livroSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(livroSelecionado);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/LivroController.cs
using LivroEC_V2.Models;
using LivroEC_V2.Repositorio;
using LivroEC_V2.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace LivroEC_V2.Controllers
{
    public class LivroController : Controller
    {
        private readonly ILivroRepositorio _livroRepositorio;

        public LivroController(ILivroRepositorio livroRepositorio)
        {
            _livroRepositorio = livroRepositorio;
        }

        [Authorize]
        public IActionResult List(string categoria)
        {
            // Código para rederizar na view a quantidade de livros no banco
            ViewBag.TotalDeLivros = _livroRepositorio.Livros.Count();

            IEnumerable<Livro> livros;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                livros = _livroRepositorio.Livros.OrderBy(l => l.LivroId);
                categoriaAtual = "Todos os livros";
            }
            else
            {
                //if (string.Equals("Política", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    livros = _livroRepositorio.Livros
                //        .Where(l => l.Categorias.CategoriaNome
                //        .Equals("Política"))
                //        .OrderBy(l => l.Titulo);
                //}
                //else
                //{
                //    livros = _livroRepositorio.Livros
                //                   .Where(l => l.Categorias.CategoriaNome
                //                   .Equals("Romance"))
                //                   .OrderBy(l => l.Titulo);
                //}

                livros = _livroRepositorio.Livros
                    .Where(l => l.Categorias.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Titulo);

                categoriaAtual = categoria;
            }

            var livrosListViewModel = new LivroListViewModel
            {
                Livros = livros,
                CategoriaAtual = categoria
            };

            return View(livrosListViewModel);
        }

        public IActionResult Details(int livroId)
        {
            var livro = _livroRepositorio.Livros.FirstOrDefault(l => l.LivroId == livroId);
            return View(livro);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Livro> livros;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                livros = _livroRepositorio.Livros.OrderBy(x => x.LivroId);
                categoriaAtual = "Todos os livros";
            }
            else
            {
                livros = _livroRepositorio.Livros
                    .Where(x => x.Titulo
                    .ToLower()
                    .Contains(searchString
                    .ToLower()));

                if(livros.Any())
                {
                    categoriaAtual = "Livros";
                }
                else
                
                    categoriaAtual = "Nenhum livro foi encontrado";
                                       
            }

            return View("~/Views/Livro/List.cshtml", new LivroListViewModel
            {
                Livros = livros,
                CategoriaAtual = categoriaAtual
            }) ;
        }
    }
}         

Views/Livro/Details.cshtml
@model Livro



<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

Views/Livro/List.cshtml
@model LivroListViewModel

@{
    ViewData["Title"] = "Listagem de Livros";
}

<div class="text-center" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); max-width: contain">
    <h1 class="display-4">@ViewData["Title"]</h1>
</div>
<hr />
<br />

<p>
    <a role="button" class="btn btn-primary" asp-action="Create">Adicionar novo livro</a>
</p>

<table class="table table-hover" id="table-livros">
    <thead>
        <tr>
            <th scope="col" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5)">Título</th>
            <th scope="col" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5)">Preco R$</th>
            <th scope="col" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5)">Categoria</th>
            <th scope="col" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); padding-left: 60px; ">Ações</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Livros) {
        <tr>
                <partial name="_LivroResumo" for="@item"></partial>
            <td>
               @* <a role="button" class="btn btn-warning" asp-action="Edit" asp-route-id="@item.LivroId">Editar</a>*@
                <a role="button" class="btn btn-secondary" asp-action="Details" asp-route-id="@item.LivroId">Detalhes</a>
               @* <a role="button" class="btn btn-danger" asp-action="Delete" asp-route-id="@item.LivroId">Deletar</a>*@
                <a role="button" class="btn btn-primary" asp-controller="CarrinhoCompra" asp-action="AdicionarItemDoCarrinhoCompra" asp-route-LivroId="@item.LivroId">Incluir no Carrinho</a>
            </td>
        </tr>
        
}
    </tbody>
</table>
<div>
    <p style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5)">Total de livros: @ViewBag.TotalDeLivros</p>
</div>